Project 1 Code Document

In [3]:
import pandas as pd

In [4]:
air_data = pd.read_csv('AirQuality_Daily_StudentVersion(in).csv')

air_data = pd.DataFrame(air_data)

#air_data

air_data.head(3)

,date,monitor_index,humidity,pressure,temperature,voc,analog_input,pm2.5_alt,pm1.0_atm,pm2.5_atm,pm10.0_atm,sensor.latitude,sensor.longitude,sensor.altitude,sensor.name
0,2/23/2024,195089,14.377667,912.884333,62.266667,51.998667,0.051333,0.1000,0.000000,0.002500,0.039667,40.050922,-101.533570,3005,Swnphd-Benklemen
1,2/23/2024,195365,12.223600,926.403000,71.193400,64.920800,0.000000,0.1800,0.004800,0.020000,0.176000,40.200330,-100.639885,2576,Swnphd-mccook
2,2/23/2024,195541,20.095750,905.670750,61.008250,68.307000,0.020000,0.1625,0.004125,0.014812,0.063937,41.128284,-101.720220,3220,Swnphd-ogallala

Client Request 1 is to find the 5 locations in Nebraska with the highest mean and median concentrations of voc, PM 2.5, and PM 10.0

In [5]:
data_grouped_location = air_data.groupby('sensor.name')


voc_locations = data_grouped_location.agg(mean_voc = ('voc', 'mean'),
                                               median_voc = ('voc','median'))
PM2_5_locations = data_grouped_location.agg(mean_PM2_5 = ('pm2.5_alt', 'mean'),
                                               median_PM2_5 = ('pm2.5_alt','median'))
PM10_locations = data_grouped_location.agg(mean_PM10 = ('pm10.0_atm', 'mean'),
                                               median_PM10 = ('pm10.0_atm','median'))


high_PM2_5_locations = PM2_5_locations.sort_values(by = ['mean_PM2_5', 'median_PM2_5'], ascending = [True,True])
high_PM10_locations = PM10_locations.sort_values(by = ['mean_PM10', 'median_PM10'], ascending = [True,True])
high_voc_locations = voc_locations.sort_values(by = ['mean_voc', 'median_voc'], ascending = [True,True])

high_voc_locations.tail(5)

                                         mean_voc  median_voc
sensor.name
Swnphd-mccook                          353.941581  381.468479
ELVPHD Norfolk HD 4                    360.833744  368.580500
Three Rivers Public Health Department  370.216208  376.810167
FCHD-YPS                               372.462720  375.383500
Swnphd-ogallala                        399.434240  423.082292

In [6]:
high_PM10_locations.tail(5)

                                                     mean_PM10  median_PM10
sensor.name
Swnphd-mccook                                       124.227336     5.372073
NCDHD O'Neill #11                                   166.132578     8.427437
#18 - Southeast District Health Department- Tec...  614.227248    11.433729
#16 - Richardson County Courthouse                  701.632446    13.305615
Broken Bow                                          929.678512    43.179094

In [7]:
high_PM2_5_locations.tail(5)

                                                    mean_PM2_5  median_PM2_5
sensor.name
#16 - Richardson County Courthouse                    6.107541      4.843750
NCDHD O'Neill #11                                     6.293831      3.500000
ELVPHD Norfolk HD 4                                   7.993607      5.437500
Ainsworth Public School #9                            8.194523      6.810417
#18 - Southeast District Health Department- Tec...    9.179178      5.825000

Client request 2 is to find what days the max values occurred and where. We are to find potential reasons for these maximums.

In [8]:
data_grouped_location_date = air_data.groupby(['sensor.name','date'])


max_voc_locations_date = data_grouped_location_date.agg(max_voc = ('voc', 'max')).sort_values(by = 'max_voc', ascending = False)
max_PM2_5_locations_date = data_grouped_location_date.agg(max_PM2_5 = ('pm2.5_alt', 'max')).sort_values(by = 'max_PM2_5', ascending = False)
max_PM10_locations_date = data_grouped_location_date.agg(max_PM10 = ('pm10.0_atm', 'max')).sort_values(by = 'max_PM10', ascending = False)

max_voc_locations_date.head(5)

                                    max_voc
sensor.name         date
Swnphd-ogallala     6/24/2024   1209.931571
SWNPHD-Imerial      10/5/2024   1135.473000
                    11/23/2024  1041.722000
ELVPHD Norfolk HD 4 10/12/2024   884.649000
SWNPHD-Imerial      10/16/2024   871.182000

In [9]:
max_PM2_5_locations_date.head(5)

                                                              max_PM2_5
sensor.name                                        date
ELVPHD Norfolk HD 4                                10/9/2024  56.633333
#18 - Southeast District Health Department- Tec... 5/14/2024  56.004167
#16 - Richardson County Courthouse                 5/14/2024  55.541667
Swnphd-ogallala                                    7/25/2024  48.737500
FCHD-YPS                                           5/14/2024  46.900000

In [10]:
max_PM10_locations_date.head(5)

                                                 max_PM10
sensor.name                        date
#16 - Richardson County Courthouse 2/18/2025  3784.682542
                                   2/19/2025  3403.435958
                                   2/20/2025  3245.613354
                                   1/21/2025  3211.046813
Broken Bow                         2/18/2025  3206.779708

Client request 3 is to find out if humidity and temperature have noticeable effects on air quality.

In [21]:
def assign_temperature(temperature):
    if temperature < 32:
        return 'Below Freezing'
    elif 32 <= temperature <= 50:
        return 'Cool'
    elif 51 <= temperature <= 70:
        return 'Warm'
    else:
        return 'Hot'

air_data['temperature_level'] = air_data['temperature'].apply(assign_temperature)

grouped_temps = air_data.groupby('temperature_level')

temp_data = grouped_temps.agg(mean_voc = ('voc', 'mean'),
                              median_voc = ('voc', 'median'),
                              mean_pm10 = ('pm10.0_atm', 'mean'),
                              median_pm10 = ('pm10.0_atm', 'median'),
                              mean_pm2_5 = ('pm2.5_alt', 'mean'),
                              median_pm2_5 = ('pm2.5_alt', 'median'))
temp_data

,mean_voc,median_voc,mean_pm10,median_pm10,mean_pm2_5,median_pm2_5
temperature_level,,,,,,
Below Freezing,257.628626,251.385875,276.080794,11.236998,4.948646,3.641667
Cool,285.435146,281.329854,143.074475,7.456146,4.559957,3.133333
Hot,281.957598,237.979896,73.964812,9.083792,6.718568,4.678714
Warm,255.916308,225.399958,84.021411,4.342583,3.375344,2.214583

In [31]:
def assign_humidity(humidity):
    if humidity < 50:
        return 'Low'
    elif 50 <= humidity < 80:
        return 'High'
    else:
        return 'Very High'

air_data['humidity_level'] = air_data['humidity'].apply(assign_humidity)

grouped_humidities = air_data.groupby('humidity_level')

humidity_data = grouped_humidities.agg(mean_voc = ('voc', 'mean'),
                              median_voc = ('voc', 'median'),
                              mean_pm10 = ('pm10.0_atm', 'mean'),
                              median_pm10 = ('pm10.0_atm', 'median'),
                              mean_pm2_5 = ('pm2.5_alt', 'mean'),
                              median_pm2_5 = ('pm2.5_alt', 'median'))
humidity_data

,mean_voc,median_voc,mean_pm10,median_pm10,mean_pm2_5,median_pm2_5
humidity_level,,,,,,
High,252.664069,197.070417,82.561133,11.062667,7.119472,5.495833
Low,279.329347,258.075292,77.880520,6.676271,5.182071,3.279167
Very High,19.395555,0.000000,536.520850,11.872094,4.793663,3.777083

Client request 4 is to analyze the data to see if there have been any AQI health risks for sensitive populations based on EPA AQI ratings.

In [38]:
def assign_unhealthy_sensitive(pm2_5):
    if pm2_5 <= 35.4:
        return 'Safe'
    if 35.5 <= pm2_5 <=55.4:
        return 'Unhealthy for Sensitive Groups'
    else:
        return 'Unsafe'

air_data['pm2_5_category'] = air_data['pm2.5_alt'].apply(assign_unhealthy_sensitive)

sensitive_only = air_data[air_data['pm2_5_category'] == 'Unhealthy for Sensitive Groups']

sensitive_only

,date,monitor_index,humidity,pressure,temperature,voc,analog_input,pm2.5_alt,pm1.0_atm,pm2.5_atm,pm10.0_atm,sensor.latitude,sensor.longitude,sensor.altitude,sensor.name,temperature_level,assign_humidity,humidity_level,pm2_5_category,pm_10_category
1341,5/14/2024,195091,36.470208,960.654000,71.090333,99.731292,0.010000,35.700000,31.409896,48.140771,60.299813,41.995426,-96.927210,1385,ELVPHD Wisner HD 5,Hot,Low,Low,Unhealthy for Sensitive Groups,Safe
1345,5/14/2024,195319,35.732375,942.238417,77.216667,226.298167,0.000000,38.525000,32.548021,47.330646,57.197542,40.589070,-98.383190,1920,South Heartland District Health Dept. Hastings...,Hot,Low,Low,Unhealthy for Sensitive Groups,Safe
1346,5/14/2024,195327,30.908500,972.626583,75.262833,78.419417,0.015792,35.616667,30.595896,45.881250,56.471104,41.766724,-96.220910,1033,ELVPHD Tekamah HD 3,Hot,Low,Low,Unhealthy for Sensitive Groups,Safe
1350,5/14/2024,195341,40.287958,958.840500,70.362667,274.631208,0.000000,44.479167,34.278979,52.773958,64.502917,40.156180,-97.175354,1438,PHS Fairbury JCHL 13,Hot,Low,Low,Unhealthy for Sensitive Groups,Safe
1351,5/14/2024,195343,33.590333,956.235417,72.873583,216.771875,0.000333,39.070833,33.963292,50.918271,60.703125,42.033070,-97.408394,1522,ELVPHD Norfolk HD 4,Hot,Low,Low,Unhealthy for Sensitive Groups,Safe
1359,5/14/2024,195367,33.245917,967.626333,74.925083,460.893250,0.009917,44.016667,34.684083,51.491208,60.560375,41.452810,-96.477740,1188,Three Rivers Public Health Department,Hot,Low,Low,Unhealthy for Sensitive Groups,Safe
1361,5/14/2024,195379,31.709708,951.872125,75.301458,306.593292,0.000000,46.900000,36.062000,59.293417,73.258167,40.877007,-97.579445,1639,FCHD-YPS,Hot,Low,Low,Unhealthy for Sensitive Groups,Safe
3111,7/24/2024,194969,29.631167,907.193708,91.100042,405.068333,0.016833,38.904167,32.210000,45.206938,55.024896,40.512820,-101.629420,3269,SWNPHD-Imerial,Hot,Low,Low,Unhealthy for Sensitive Groups,Safe
3112,7/24/2024,195089,30.775750,916.040167,89.639250,472.215750,0.050042,39.216667,32.589000,46.913958,58.405750,40.050922,-101.533570,3005,Swnphd-Benklemen,Hot,Low,Low,Unhealthy for Sensitive Groups,Safe
3127,7/24/2024,195355,31.722292,894.725542,90.504250,133.371333,0.000000,37.191667,30.167146,43.357542,53.521083,41.569260,-101.689420,3661,WCDHD Arthur High School 28,Hot,Low,Low,Unhealthy for Sensitive Groups,Safe
3135,7/24/2024,195541,28.373125,908.330708,92.315167,528.603792,0.016500,42.158333,29.438458,43.837667,53.666396,41.128284,-101.720220,3220,Swnphd-ogallala,Hot,Low,Low,Unhealthy for Sensitive Groups,Safe
3136,7/25/2024,194969,24.848667,907.278000,94.223667,314.560042,0.016417,44.433333,33.691125,49.004625,60.005750,40.512820,-101.629420,3269,SWNPHD-Imerial,Hot,Low,Low,Unhealthy for Sensitive Groups,Safe
3137,7/25/2024,195089,25.962500,916.260833,92.782042,446.174500,0.050000,44.379167,33.967771,49.938125,62.879104,40.050922,-101.533570,3005,Swnphd-Benklemen,Hot,Low,Low,Unhealthy for Sensitive Groups,Safe
3140,7/25/2024,195315,35.482333,950.250625,91.210667,124.308917,0.037542,35.866667,28.022625,42.725625,51.376479,40.100227,-99.363140,1984,TRPHD Harlan Co. Courthouse 24,Hot,Low,Low,Unhealthy for Sensitive Groups,Safe
3145,7/25/2024,195333,39.191667,936.050167,88.286625,575.083667,0.006542,42.029167,30.991521,46.411146,57.848667,40.780205,-99.740486,2392,TRPHD Dawson Co. Courthouse 25,Hot,Low,Low,Unhealthy for Sensitive Groups,Safe
3150,7/25/2024,195347,33.855458,931.087583,94.691750,183.769958,0.080958,40.904167,29.195042,43.320062,52.673917,42.547630,-99.856430,2519,Ainsworth Public School #9,Hot,Low,Low,Unhealthy for Sensitive Groups,Safe
3152,7/25/2024,195355,26.802750,894.668250,92.919458,119.723542,0.000000,42.320833,31.336646,46.354292,57.954313,41.569260,-101.689420,3661,WCDHD Arthur High School 28,Hot,Low,Low,Unhealthy for Sensitive Groups,Safe
3154,7/25/2024,195362,39.757458,933.506917,89.533583,124.760250,0.000000,43.166667,30.702979,44.379125,54.891937,41.396297,-99.645035,2582,Broken Bow,Hot,Low,Low,Unhealthy for Sensitive Groups,Safe
3155,7/25/2024,195365,24.006958,930.015625,96.913917,396.009000,0.000000,38.412500,29.809979,44.073771,55.115333,40.200330,-100.639885,2576,Swnphd-mccook,Hot,Low,Low,Unhealthy for Sensitive Groups,Safe
3160,7/25/2024,195541,25.127792,908.301292,95.126375,443.738250,0.016250,48.737500,30.641813,47.412542,58.741667,41.128284,-101.720220,3220,Swnphd-ogallala,Hot,Low,Low,Unhealthy for Sensitive Groups,Safe
4132,9/5/2024,195329,38.781750,959.652458,84.350000,252.977583,0.010042,36.366667,29.775833,45.030938,52.568208,42.911533,-98.847984,1810,Lower Niobrara NRD Butte 10,Hot,Low,Low,Unhealthy for Sensitive Groups,Safe
4140,9/5/2024,195361,43.931583,952.991417,80.704375,543.295875,0.040000,37.933333,31.783167,45.140896,55.744646,42.457850,-98.646736,1990,NCDHD O'Neill #11,Hot,Low,Low,Unhealthy for Sensitive Groups,Safe

In [39]:
def assign_unhealthy_sensitive2(pm_10):
    if pm_10 < 154:
        return 'Safe'
    elif 155 <= pm_10 <= 254:
        return 'Unhealthy for Sensitive Groups'
    else:
        return 'Unsafe'

air_data['pm_10_category'] = air_data['pm10.0_atm'].apply(assign_unhealthy_sensitive2)

sensitive_only2 = air_data[air_data['pm_10_category'] == 'Unhealthy for Sensitive Groups']

sensitive_only2

,date,monitor_index,humidity,pressure,temperature,voc,analog_input,pm2.5_alt,pm1.0_atm,pm2.5_atm,pm10.0_atm,sensor.latitude,sensor.longitude,sensor.altitude,sensor.name,temperature_level,assign_humidity,humidity_level,pm2_5_category,pm_10_category
2144,6/14/2024,195383,28.215333,941.437667,86.294792,504.586833,0.05,1.616667,229.848167,230.482438,231.757021,41.779380,-99.13804,2174,Loup Basin Public Health Department,Hot,Low,Low,Safe,Unhealthy for Sensitive Groups
2443,6/27/2024,195089,37.042250,907.131625,90.093000,430.016958,0.05,2.333333,187.669333,188.156771,188.977500,40.050922,-101.53357,3005,Swnphd-Benklemen,Hot,Low,Low,Safe,Unhealthy for Sensitive Groups
6076,12/8/2024,195317,NaN,NaN,NaN,NaN,0.06,5.670833,196.998833,198.986375,200.798396,40.062200,-95.60240,1023,#16 - Richardson County Courthouse,Hot,Very High,Very High,Safe,Unhealthy for Sensitive Groups

Client request 5 is to find out analyze the data to see if sensor altitude has an impact on air quality values.

In [51]:
def assign_altitude(altitude):
    if altitude < 1600:
        return 'Low'
    elif 1600 <= altitude < 2600:
        return 'Medium'
    else:
        return 'High'

air_data['altitude_category'] = air_data['sensor.altitude'].apply(assign_altitude)

grouped_altitude = air_data.groupby('altitude_category').agg(mean_voc = ('voc', 'mean'),
                              median_voc = ('voc', 'median'),
                              mean_pm10 = ('pm10.0_atm', 'mean'),
                              median_pm10 = ('pm10.0_atm', 'median'),
                              mean_pm2_5 = ('pm2.5_alt', 'mean'),
                              median_pm2_5 = ('pm2.5_alt', 'median'))
grouped_altitude

,mean_voc,median_voc,mean_pm10,median_pm10,mean_pm2_5,median_pm2_5
altitude_category,,,,,,
High,309.155679,310.181583,8.597666,4.384385,4.244620,2.383333
Low,232.665885,180.565583,133.205752,9.336208,6.123510,4.372917
Medium,284.736979,268.011818,116.533900,7.543604,5.336557,3.492857